### ISSUE TITLE
Inconsistent ordering Init events, compared to other tracking attributes

### ISSUE THREAD

**Issue by jsenior** [teamsodo/sodo#3]
![image](https://user-images.githubusercontent.com/206203/29105120-9975d4fa-7c7f-11e7-8833-b00f61efbf55.png)

spot the odd one out ;)

**Comment by spoon16** [comment]
@jsenior This is intended. CLI currently allows you to switch them. You can run `sodo backlog init` or `sodo init backlog`. I order them in the tracking the way they were executed. I did that because I wanted to see what order people prefer.

**Comment by jsenior** [comment]
Got it. That approach incurs a slight cost downstream when we do analysis in Mixpanel (we need to account for two variants in funnel steps for one event). Could we not make a call on it now?

**Comment by spoon16** [comment]
we can make a call or I can add another attribute that is sorted, so you have consistency downstream

**Comment by jsenior** [comment]
Let's add sorted attrib, that way we both get the outcome we want. I can also setup a metric in mixpanel to track user preference over time for you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by duffmeister** [comment]
We should just make a call on which to use. It's going to have downstream impacts on user training (having to explain you can do it either way), adoption (people getting confused which way round it is and using different ways for different things and blaming us), public docs and tutorials (blog posts and community presentations where people say one way then have to defend in the comments or Q&A) etc.

**Comment by spoon16** [comment]
I want to see three customers play with it before we make a decision. I sorted the command and added spec logging for the target resource. This needs more work, but you can provide feedback re: is this what you want?

```
analytics.track({
  userId: '4ef8cce0-70b1-11e7-b1ab-8df70e829023',
  event: 'Command',
  properties: {
    command: [
      'backlog',
      'init'
    ],
    rawCommand: [
      'backlog',
      'init'
    ],
    spec: {
      config: {
        description: 'The SODO backlog is managed in JIRA @ https://f9teams.atlassian.net/SODO
Adminitrator: eric@f9teams.com
',
        projectKey: 'SODO',
        url: 'https://f9teams.atlassian.net/'
      },
      id: 'jira',
      label: 'product'
    }
  }
});
```
